//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace CIR.Serialization {
    using System.Xml.Serialization;
    using System.Xml.Linq;
    using TextType = Ccom.TextType;
    using CodeType = Ccom.CodeType;
    using BusinessObjectDocumentType = Oagis.BusinessObjectDocumentType;
    using Ccom;
    using Oagis;
    

    public interface Namespace
    {
        public const string URI = "http://www.openoandm.org/ws-cir/";
        public readonly static XNamespace XNAMESPACE;

        static Namespace() {
            XNAMESPACE = XNamespace.Get(URI);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CreateRegistry {
        
        private Registry[] registryField;
        
        private bool createCIRIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registry")]
        public Registry[] Registry {
            get {
                return this.registryField;
            }
            set {
                this.registryField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCIRID {
            get {
                return this.createCIRIDField;
            }
            set {
                this.createCIRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class Registry {
        
        private IDType idField;
        
        private TextType[] descriptionField;
        
        private Category[] categoryField;
        
        /// <remarks/>
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public TextType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public Category[] Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class Category {
        
        private IDType idField;
        
        private IDType categorySourceIDField;
        
        private TextType[] descriptionField;
        
        private Entry[] entryField;
        
        /// <remarks/>
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public TextType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public Entry[] Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class Entry {
        
        private IDType iDInSourceField;
        
        private IDType sourceIDField;
        
        private string cIRIDField;
        
        private IDType sourceOwnerIDField;
        
        private TextType nameField;
        
        private TextType[] descriptionField;
        
        private bool inactiveField;
        
        private bool inactiveFieldSpecified;
        
        private Property[] propertyField;
        
        /// <remarks/>
        public IDType IDInSource {
            get {
                return this.iDInSourceField;
            }
            set {
                this.iDInSourceField = value;
            }
        }
        
        /// <remarks/>
        public IDType SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string CIRID {
            get {
                return this.cIRIDField;
            }
            set {
                this.cIRIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType SourceOwnerID {
            get {
                return this.sourceOwnerIDField;
            }
            set {
                this.sourceOwnerIDField = value;
            }
        }
        
        /// <remarks/>
        public TextType Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public TextType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Inactive {
            get {
                return this.inactiveField;
            }
            set {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InactiveSpecified {
            get {
                return this.inactiveFieldSpecified;
            }
            set {
                this.inactiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public Property[] Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class Property {
        
        private IDType idField;
        
        private PropertyValue[] propertyValueField;
        
        private CodeType dataTypeField;
        
        /// <remarks/>
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyValue")]
        public PropertyValue[] PropertyValue {
            get {
                return this.propertyValueField;
            }
            set {
                this.propertyValueField = value;
            }
        }
        
        /// <remarks/>
        public CodeType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class PropertyValue {
        
        private IDType keyField;
        
        private string valueField;
        
        private CodeType unitOfMeasureField;
        
        /// <remarks/>
        public IDType Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public CodeType UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
    }
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CreateRegistryResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CreateEquivalentEntries {
        
        private EquivalentEntry[] equivalentEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EquivalentEntry")]
        public EquivalentEntry[] EquivalentEntry {
            get {
                return this.equivalentEntryField;
            }
            set {
                this.equivalentEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class EquivalentEntry {
        
        private IDType existingIDInSourceField;
        
        private IDType existingSourceIDField;
        
        private IDType registryIDField;
        
        private IDType categoryIDField;
        
        private IDType categorySourceIDField;
        
        private Entry entryField;
        
        /// <remarks/>
        public IDType ExistingIDInSource {
            get {
                return this.existingIDInSourceField;
            }
            set {
                this.existingIDInSourceField = value;
            }
        }
        
        /// <remarks/>
        public IDType ExistingSourceID {
            get {
                return this.existingSourceIDField;
            }
            set {
                this.existingSourceIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
        
        /// <remarks/>
        public Entry Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CreateEquivalentEntriesResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class UpdateRegistry {
        
        private Registry[] registryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registry")]
        public Registry[] Registry {
            get {
                return this.registryField;
            }
            set {
                this.registryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class UpdateRegistryResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class UpdateEntryCIRID {
        
        private string[] oldCIRIDField;
        
        private string newCIRIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OldCIRID")]
        public string[] OldCIRID {
            get {
                return this.oldCIRIDField;
            }
            set {
                this.oldCIRIDField = value;
            }
        }
        
        /// <remarks/>
        public string NewCIRID {
            get {
                return this.newCIRIDField;
            }
            set {
                this.newCIRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class UpdateEntryCIRIDResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteRegistry {
        
        private IDType registryIDField;
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteRegistryResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteCategory {
        
        private IDType registryIDField;
        
        private IDType categoryIDField;
        
        private IDType categorySourceIDField;
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteCategoryResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteEntries {
        
        private EntryIdentifier[] entryIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryIdentifier")]
        public EntryIdentifier[] EntryIdentifier {
            get {
                return this.entryIdentifierField;
            }
            set {
                this.entryIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class EntryIdentifier {
        
        private IDType registryIDField;
        
        private IDType categoryIDField;
        
        private IDType categorySourceIDField;
        
        private IDType entryIDInSourceField;
        
        private IDType entrySourceIDField;
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType EntryIDInSource {
            get {
                return this.entryIDInSourceField;
            }
            set {
                this.entryIDInSourceField = value;
            }
        }
        
        /// <remarks/>
        public IDType EntrySourceID {
            get {
                return this.entrySourceIDField;
            }
            set {
                this.entrySourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteEntriesResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeleteProperties {
        
        private PropertyIdentifier[] propertyIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyIdentifier")]
        public PropertyIdentifier[] PropertyIdentifier {
            get {
                return this.propertyIdentifierField;
            }
            set {
                this.propertyIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class PropertyIdentifier {
        
        private IDType registryIDField;
        
        private IDType categoryIDField;
        
        private IDType categorySourceIDField;
        
        private IDType entryIDInSourceField;
        
        private IDType entrySourceIDField;
        
        private IDType propertyIDField;
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType EntryIDInSource {
            get {
                return this.entryIDInSourceField;
            }
            set {
                this.entryIDInSourceField = value;
            }
        }
        
        /// <remarks/>
        public IDType EntrySourceID {
            get {
                return this.entrySourceIDField;
            }
            set {
                this.entrySourceIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType PropertyID {
            get {
                return this.propertyIDField;
            }
            set {
                this.propertyIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DeletePropertiesResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class GetRegistry {
        
        private Filter[] filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Filter")]
        public Filter[] Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class Filter {
        
        private RegistryFilter registryFilterField;
        
        private CategoryFilter categoryFilterField;
        
        private EntryFilter entryFilterField;
        
        private PropertyFilter propertyFilterField;
        
        /// <remarks/>
        public RegistryFilter RegistryFilter {
            get {
                return this.registryFilterField;
            }
            set {
                this.registryFilterField = value;
            }
        }
        
        /// <remarks/>
        public CategoryFilter CategoryFilter {
            get {
                return this.categoryFilterField;
            }
            set {
                this.categoryFilterField = value;
            }
        }
        
        /// <remarks/>
        public EntryFilter EntryFilter {
            get {
                return this.entryFilterField;
            }
            set {
                this.entryFilterField = value;
            }
        }
        
        /// <remarks/>
        public PropertyFilter PropertyFilter {
            get {
                return this.propertyFilterField;
            }
            set {
                this.propertyFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class RegistryFilter {
        
        private IDType idField;
        
        /// <remarks/>
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class CategoryFilter {
        
        private IDType idField;
        
        private IDType categorySourceIDField;
        
        /// <remarks/>
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class EntryFilter {
        
        private IDType iDInSourceField;
        
        private IDType sourceIDField;
        
        private string cIRIDField;
        
        private IDType sourceOwnerIDField;
        
        private TextType nameField;
        
        private bool inactiveField;
        
        private bool inactiveFieldSpecified;
        
        /// <remarks/>
        public IDType IDInSource {
            get {
                return this.iDInSourceField;
            }
            set {
                this.iDInSourceField = value;
            }
        }
        
        /// <remarks/>
        public IDType SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string CIRID {
            get {
                return this.cIRIDField;
            }
            set {
                this.cIRIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType SourceOwnerID {
            get {
                return this.sourceOwnerIDField;
            }
            set {
                this.sourceOwnerIDField = value;
            }
        }
        
        /// <remarks/>
        public TextType Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool Inactive {
            get {
                return this.inactiveField;
            }
            set {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InactiveSpecified {
            get {
                return this.inactiveFieldSpecified;
            }
            set {
                this.inactiveFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class PropertyFilter {
        
        private IDType idField;
        
        private CodeType dataTypeField;
        
        /// <remarks/>
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CodeType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class GetRegistryResponse {
        
        private Registry[] registryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registry")]
        public Registry[] Registry {
            get {
                return this.registryField;
            }
            set {
                this.registryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class GetEquivalentEntries {
        
        private EntryIdentifier[] entryIdentifierField;
        
        private IDType[] targetSourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryIdentifier")]
        public EntryIdentifier[] EntryIdentifier {
            get {
                return this.entryIdentifierField;
            }
            set {
                this.entryIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetSourceID")]
        public IDType[] TargetSourceID {
            get {
                return this.targetSourceIDField;
            }
            set {
                this.targetSourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class GetEquivalentEntriesResponse {
        
        private Registry[] registryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registry")]
        public Registry[] Registry {
            get {
                return this.registryField;
            }
            set {
                this.registryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class GetEntriesByCIRID {
        
        private string existingCIRIDField;
        
        private IDType[] targetSourceIDField;
        
        /// <remarks/>
        public string ExistingCIRID {
            get {
                return this.existingCIRIDField;
            }
            set {
                this.existingCIRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetSourceID")]
        public IDType[] TargetSourceID {
            get {
                return this.targetSourceIDField;
            }
            set {
                this.targetSourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class GetEntriesByCIRIDResponse {
        
        private Registry[] registryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registry")]
        public Registry[] Registry {
            get {
                return this.registryField;
            }
            set {
                this.registryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CreateRegistryFault {
        
        private TextType descriptionField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CreateCategoryFault {
        
        private TextType descriptionField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class RegistryNotFoundFault {
        
        private TextType descriptionField;
        
        private RegistryIdentifier registryIdentifierField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public RegistryIdentifier RegistryIdentifier {
            get {
                return this.registryIdentifierField;
            }
            set {
                this.registryIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class RegistryIdentifier {
        
        private IDType registryIDField;
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class CategoryNotFoundFault {
        
        private TextType descriptionField;
        
        private CategoryIdentifier categoryIdentifierField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public CategoryIdentifier CategoryIdentifier {
            get {
                return this.categoryIdentifierField;
            }
            set {
                this.categoryIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
    public partial class CategoryIdentifier {
        
        private IDType registryIDField;
        
        private IDType categoryIDField;
        
        private IDType categorySourceIDField;
        
        /// <remarks/>
        public IDType RegistryID {
            get {
                return this.registryIDField;
            }
            set {
                this.registryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public IDType CategorySourceID {
            get {
                return this.categorySourceIDField;
            }
            set {
                this.categorySourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class EntryNotFoundFault {
        
        private TextType descriptionField;
        
        private EntryIdentifier entryIdentifierField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public EntryIdentifier EntryIdentifier {
            get {
                return this.entryIdentifierField;
            }
            set {
                this.entryIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class PropertyNotFoundFault {
        
        private TextType descriptionField;
        
        private PropertyIdentifier propertyIdentifierField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public PropertyIdentifier PropertyIdentifier {
            get {
                return this.propertyIdentifierField;
            }
            set {
                this.propertyIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DuplicateEntryFault {
        
        private TextType descriptionField;
        
        private EntryIdentifier entryIdentifierField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public EntryIdentifier EntryIdentifier {
            get {
                return this.entryIdentifierField;
            }
            set {
                this.entryIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openoandm.org/ws-cir/", IsNullable=false)]
    public partial class DuplicatePropertyFault {
        
        private TextType descriptionField;
        
        private PropertyIdentifier propertyIdentifierField;
        
        /// <remarks/>
        public TextType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public PropertyIdentifier PropertyIdentifier {
            get {
                return this.propertyIdentifierField;
            }
            set {
                this.propertyIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("AcknowledgeEquivalentEntries",Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class AcknowledgeEquivalentEntriesBOD : BusinessObjectDocumentType {
        
        private AcknowledgeEquivalentEntriesDataArea dataAreaField;
        
        /// <remarks/>
        public AcknowledgeEquivalentEntriesDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class AcknowledgeEquivalentEntriesDataArea {
        
        private AcknowledgeType acknowledgeField;
        
        private EntryNotFoundFault[] entryNotFoundFaultField;
        
        private RegistryNotFoundFault[] registryNotFoundFaultField;
        
        private CategoryNotFoundFault[] categoryNotFoundFaultField;
        
        private DuplicateEntryFault[] duplicateEntryFaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public AcknowledgeType Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public EntryNotFoundFault[] EntryNotFoundFault {
            get {
                return this.entryNotFoundFaultField;
            }
            set {
                this.entryNotFoundFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public RegistryNotFoundFault[] RegistryNotFoundFault {
            get {
                return this.registryNotFoundFaultField;
            }
            set {
                this.registryNotFoundFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CategoryNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public CategoryNotFoundFault[] CategoryNotFoundFault {
            get {
                return this.categoryNotFoundFaultField;
            }
            set {
                this.categoryNotFoundFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DuplicateEntryFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public DuplicateEntryFault[] DuplicateEntryFault {
            get {
                return this.duplicateEntryFaultField;
            }
            set {
                this.duplicateEntryFaultField = value;
            }
        }
    }
    
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("AcknowledgeRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class AcknowledgeRegistryBOD : BusinessObjectDocumentType {
        
        private AcknowledgeRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public AcknowledgeRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class AcknowledgeRegistryDataArea {
        
        private AcknowledgeType acknowledgeField;
        
        private CreateRegistryFault[] createRegistryFaultField;
        
        private CreateCategoryFault[] createCategoryFaultField;
        
        private DuplicateEntryFault[] duplicateEntryFaultField;
        
        private DuplicatePropertyFault[] duplicatePropertyFaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public AcknowledgeType Acknowledge 
        {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreateRegistryFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public CreateRegistryFault[] CreateRegistryFault {
            get {
                return this.createRegistryFaultField;
            }
            set {
                this.createRegistryFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreateCategoryFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public CreateCategoryFault[] CreateCategoryFault {
            get {
                return this.createCategoryFaultField;
            }
            set {
                this.createCategoryFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DuplicateEntryFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public DuplicateEntryFault[] DuplicateEntryFault {
            get {
                return this.duplicateEntryFaultField;
            }
            set {
                this.duplicateEntryFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DuplicatePropertyFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public DuplicatePropertyFault[] DuplicatePropertyFault {
            get {
                return this.duplicatePropertyFaultField;
            }
            set {
                this.duplicatePropertyFaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("CancelCategory", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class CancelCategoryBOD : BusinessObjectDocumentType {
        
        private CancelCategoryDataArea dataAreaField;
        
        /// <remarks/>
        public CancelCategoryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class CancelCategoryDataArea {
        
        private CancelType cancelField;
        
        private DeleteCategory deleteCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public CancelType Cancel {
            get {
                return this.cancelField;
            }
            set {
                this.cancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        public DeleteCategory DeleteCategory {
            get {
                return this.deleteCategoryField;
            }
            set {
                this.deleteCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("CancelEntries", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class CancelEntriesBOD : BusinessObjectDocumentType {
        
        private CancelEntriesDataArea dataAreaField;
        
        /// <remarks/>
        public CancelEntriesDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class CancelEntriesDataArea {
        
        private CancelType cancelField;
        
        private EntryIdentifier[] deleteEntriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public CancelType Cancel {
            get {
                return this.cancelField;
            }
            set {
                this.cancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public EntryIdentifier[] DeleteEntries {
            get {
                return this.deleteEntriesField;
            }
            set {
                this.deleteEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("CancelProperties", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class CancelPropertiesBOD : BusinessObjectDocumentType {
        
        private CancelPropertiesDataArea dataAreaField;
        
        /// <remarks/>
        public CancelPropertiesDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class CancelPropertiesDataArea {
        
        private CancelType cancelField;
        
        private PropertyIdentifier[] deletePropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public CancelType Cancel {
            get {
                return this.cancelField;
            }
            set {
                this.cancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PropertyIdentifier[] DeleteProperties {
            get {
                return this.deletePropertiesField;
            }
            set {
                this.deletePropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("CancelRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class CancelRegistryBOD : BusinessObjectDocumentType {
        
        private CancelRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public CancelRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class CancelRegistryDataArea {
        
        private CancelType cancelField;
        
        private DeleteRegistry deleteRegistryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public CancelType Cancel {
            get {
                return this.cancelField;
            }
            set {
                this.cancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        public DeleteRegistry DeleteRegistry {
            get {
                return this.deleteRegistryField;
            }
            set {
                this.deleteRegistryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ChangeEntryCIRID", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ChangeEntryCIRIDBOD : BusinessObjectDocumentType {
        
        private ChangeEntryCIRIDDataArea dataAreaField;
        
        /// <remarks/>
        public ChangeEntryCIRIDDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ChangeEntryCIRIDDataArea {
        
        private ChangeType changeField;
        
        private UpdateEntryCIRID updateEntryCIRIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ChangeType Change {
            get {
                return this.changeField;
            }
            set {
                this.changeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        public UpdateEntryCIRID UpdateEntryCIRID {
            get {
                return this.updateEntryCIRIDField;
            }
            set {
                this.updateEntryCIRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ChangeRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ChangeRegistryBOD : BusinessObjectDocumentType {
        
        private ChangeRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public ChangeRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ChangeRegistryDataArea {
        
        private ChangeType changeField;
        
        private Registry[] updateRegistryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ChangeType Change {
            get {
                return this.changeField;
            }
            set {
                this.changeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Registry[] UpdateRegistry {
            get {
                return this.updateRegistryField;
            }
            set {
                this.updateRegistryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("GetEquivalentEntries", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class GetEquivalentEntriesBOD : BusinessObjectDocumentType {
        
        private GetEquivalentEntriesDataArea dataAreaField;
        
        /// <remarks/>
        public GetEquivalentEntriesDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class GetEquivalentEntriesDataArea {
        
        private ProcessType processField;
        
        private GetEquivalentEntries getEquivalentEntriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ProcessType Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        public GetEquivalentEntries GetEquivalentEntries {
            get {
                return this.getEquivalentEntriesField;
            }
            set {
                this.getEquivalentEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("GetEntriesByCIRID", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class GetEntriesByCIRIDBOD : BusinessObjectDocumentType {
        
        private GetEntriesByCIRIDDataArea dataAreaField;
        
        /// <remarks/>
        public GetEntriesByCIRIDDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class GetEntriesByCIRIDDataArea {
        
        private ProcessType processField;
        
        private GetEntriesByCIRID getEntriesByCIRIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ProcessType Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        public GetEntriesByCIRID GetEntriesByCIRID {
            get {
                return this.getEntriesByCIRIDField;
            }
            set {
                this.getEntriesByCIRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("GetRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class GetRegistryBOD : BusinessObjectDocumentType {
        
        private GetRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public GetRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class GetRegistryDataArea {
        
        private ProcessType processField;
        
        private Filter[] getRegistryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ProcessType Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Filter[] GetRegistry {
            get {
                return this.getRegistryField;
            }
            set {
                this.getRegistryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ProcessEquivalentEntries", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ProcessEquivalentEntriesBOD : BusinessObjectDocumentType {
        
        private ProcessEquivalentEntriesDataArea dataAreaField;
        
        /// <remarks/>
        public ProcessEquivalentEntriesDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ProcessEquivalentEntriesDataArea {
        
        private ProcessType processField;
        
        private EquivalentEntry[] createEquivalentEntriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ProcessType Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public EquivalentEntry[] CreateEquivalentEntries {
            get {
                return this.createEquivalentEntriesField;
            }
            set {
                this.createEquivalentEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ProcessRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ProcessRegistryBOD : BusinessObjectDocumentType {
        
        private ProcessRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public ProcessRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ProcessRegistryDataArea {
        
        private ProcessType processField;
        
        private CreateRegistry createRegistryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ProcessType Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        public CreateRegistry CreateRegistry {
            get {
                return this.createRegistryField;
            }
            set {
                this.createRegistryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("RespondRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class RespondRegistryBOD : BusinessObjectDocumentType {
        
        private RespondRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public RespondRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class RespondRegistryDataArea {
        
        private RespondType respondField;
        
        private RegistryNotFoundFault[] registryNotFoundFaultField;
        
        private CategoryNotFoundFault[] categoryNotFoundFaultField;
        
        private EntryNotFoundFault[] entryNotFoundFaultField;
        
        private PropertyNotFoundFault[] propertyNotFoundFaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public RespondType Respond {
            get {
                return this.respondField;
            }
            set {
                this.respondField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public RegistryNotFoundFault[] RegistryNotFoundFault {
            get {
                return this.registryNotFoundFaultField;
            }
            set {
                this.registryNotFoundFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CategoryNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public CategoryNotFoundFault[] CategoryNotFoundFault {
            get {
                return this.categoryNotFoundFaultField;
            }
            set {
                this.categoryNotFoundFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public EntryNotFoundFault[] EntryNotFoundFault {
            get {
                return this.entryNotFoundFaultField;
            }
            set {
                this.entryNotFoundFaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyNotFoundFault", Namespace="http://www.openoandm.org/ws-cir/")]
        public PropertyNotFoundFault[] PropertyNotFoundFault {
            get {
                return this.propertyNotFoundFaultField;
            }
            set {
                this.propertyNotFoundFaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ShowEquivalentEntries",Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ShowEquivalentEntriesBOD : BusinessObjectDocumentType {
        
        private ShowEquivalentEntriesDataArea dataAreaField;
        
        /// <remarks/>
        public ShowEquivalentEntriesDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ShowEquivalentEntriesDataArea {
        
        private ShowType showField;
        
        private Registry[] getEquivalentEntriesResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ShowType Show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Registry[] GetEquivalentEntriesResponse {
            get {
                return this.getEquivalentEntriesResponseField;
            }
            set {
                this.getEquivalentEntriesResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ShowEntriesByCIRID", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ShowEntriesByCIRIDBOD : BusinessObjectDocumentType {
        
        private ShowEntriesByCIRIDDataArea dataAreaField;
        
        /// <remarks/>
        public ShowEntriesByCIRIDDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ShowEntriesByCIRIDDataArea {
        
        private ShowType showField;
        
        private Registry[] getEntriesByCIRIDResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ShowType Show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Registry[] GetEntriesByCIRIDResponse {
            get {
                return this.getEntriesByCIRIDResponseField;
            }
            set {
                this.getEntriesByCIRIDResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openoandm.org/ws-cir/bod/")]
    [System.Xml.Serialization.XmlRootAttribute("ShowRegistry", Namespace="http://www.openoandm.org/ws-cir/bod/", IsNullable=false)]
    public partial class ShowRegistryBOD : BusinessObjectDocumentType {
        
        private ShowRegistryDataArea dataAreaField;
        
        /// <remarks/>
        public ShowRegistryDataArea DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openoandm.org/ws-cir/bod/")]
    public partial class ShowRegistryDataArea {
        
        private ShowType showField;
        
        private Registry[] getRegistryResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.openapplications.org/oagis/9")]
        public ShowType Show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.openoandm.org/ws-cir/")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Registry[] GetRegistryResponse {
            get {
                return this.getRegistryResponseField;
            }
            set {
                this.getRegistryResponseField = value;
            }
        }
    }
}
